### ISSUE TITLE
/board 로 접속시 에러

### ISSUE THREAD

**Issue by hhy4761** [hhy4761/2022fall_41_OSS#12]
## (node:64279) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time

router.js 에서 /board 부분 처리하는 로직이 변경되고, 해당 오류가 발생하는데 확인해주시면 감사하겠습니다.

**Comment by wjieun** [comment]
api.localhost 로 인해 에러 나는 상황으로, 127.0.0.1로 바꿔 해결하였습니다.
해당 내용 수정하여 커밋하겠습니다.
