### ISSUE TITLE
회원가입 중복확인, 비밀번호 표기 오류

### ISSUE THREAD

**Issue by jaebin-code** [hhy4761/2022fall_41_OSS#18]
1. 회원가입 페이지에 아이디 및 닉네임 중복 확인 버그

아이디와 닉네임이 빈칸인 경우에 중복 확인이 Pass되는 현상

2. 비밀번호 input type을 text에서 password로 수정

**Comment by wjieun** [comment]
오류 수정하여 pr 하였습니다
