### ISSUE TITLE
fetch 경로 수정

### ISSUE THREAD

**Issue by jaebin-code** [hhy4761/2022fall_41_OSS#6]
fetch 경로 중복 부분, /checkId 앞에 /apis붙이는 식으로 수정하면 될까요?

**Comment by hhy4761** [comment]
네 프론트에서 설정한 url과 api url이 겹칠 것 같아서 api의 url을 변경하였습니다. 
기존에 api 요청해주신 url 앞에 /apis 붙여주시면 감사하겠습니다.

**Comment by jaebin-code** [comment]
네 감사합니다.
