### ISSUE TITLE
게시판 작성일시 변수명 불일치

### ISSUE THREAD

**Issue by wjieun** [hhy4761/2022fall_41_OSS#8]
게시판 작성일시 변수명이
sqlite에는 created_at으로 설정되어 있고
apis/listBoard에는 createdAt으로 설정되어 있습니다.

어느 규칙을 따르면 될까요?

**Comment by hhy4761** [comment]
created_at으로 통일해주시기 바랍니다.

**Comment by hhy4761** [comment]
"#8 created_at 표기 수정 오류" 커밋 메세지로 커밋하여 해당 이슈 해결하였습니다. 
확인해주시면 감사하겠습니다.

**Comment by wjieun** [comment]
확인하겠습니다 :)
